### ISSUE TITLE
Access to sentinel1corrected module

### ISSUE THREAD

**Issue by RemiSahl** [nansencenter/sentinel1ice#7]
Hello,

Do you know when you will release the sentinel1corrected module ? 
I see it was closed source as of last year (https://github.com/nansencenter/sentinel1ice/issues/3) and I was wondering if there was any news on the subject.

Thanks in advance.

**Comment by akorosov** [comment]
Hi @RemiSahl ,
it will remain closed source for some time. Maybe ESA will release perfectly corrected Sentinel-1 data, then this will not be needed anymore.

May I ask how do you want to use the sentinel1ice and maybe there is a room for collaboration?
You can also write directly to anton.korosov@nersc.no

Best regards!
Anton
